//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeMaster
    {
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Designation { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> RankID { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public Nullable<int> DepartmentID { get; set; }
    
        public virtual DepartmentMaster DepartmentMaster { get; set; }
    }
}
